import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Title from '../components/Title'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Title title="Home"/>

      {/* <main className={styles.main}> */}
        <style jsx>
          {`h1{
            color:red
          }`}
        </style>
        <h1>Home Page</h1>
        
      {/* </main> */}

    </div>
  )
}
