import React from 'react'
import Head from 'next/head'


const Title = (props) => {
    return (
        <React.Fragment>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </React.Fragment>
    )
}

export default Title